//
//  UIHelper.m
//  Generated by Framework Auto Builder
//
//  Created on 2025-06-12.
//

#import "UIHelper.h"

@implementation UIHelper

+ (UIColor *)colorFromHexString {
    return nil;
}

+ (UIColor *)colorFromHexString:(NSString *)hexString {
    return nil;
}

+ (NSString *)hexStringFromColor {
    return @"";
}

+ (UIImage * _Nullable)imageWithColor:(UIColor *)color {
    return nil;
}

+ (UIImage * _Nullable)resizeImage:(UIImage *)image {
    return nil;
}

+ (UIImage * _Nullable)cropImage:(UIImage *)image {
    return nil;
}

+ (UIImage * _Nullable)roundedImage:(UIImage *)image {
    return nil;
}

+ (void)addShadowToView:(UIView *)viewoffset:(CGSize)offsetradius:(CGFloat)radiusopacity:(CGFloat)opacity {
    // TODO: Implement this method
}

+ (void)addBorderToView:(UIView *)viewwidth:(CGFloat)widthcolor:(UIColor *)color {
    // TODO: Implement this method
}

+ (void)addGradientToView:(UIView *)viewstartColor:(UIColor *)startColorendColor:(UIColor *)endColor {
    // TODO: Implement this method
}

+ (void)animateView:(UIView *)viewtype:(AnimationType)typeduration:(NSTimeInterval)duration {
    // TODO: Implement this method
}

+ (void)fadeInView:(UIView *)view {
    // TODO: Implement this method
}

+ (void)fadeOutView:(UIView *)view {
    // TODO: Implement this method
}

+ (void)showAlertInViewController:(UIViewController *)viewControllertitle:(NSString *)titlemessage:(NSString *)messagestyle:(AlertStyle)style {
    // TODO: Implement this method
}

+ (void)showActionSheetInViewController:(UIViewController *)viewControllertitle:(NSString * _Nullable)titlemessage:(NSString * _Nullable)message {
    // TODO: Implement this method
}

+ (void)centerView:(UIView *)view {
    // TODO: Implement this method
}

+ (void)constrainView:(UIView *)viewsuperview:(UIView *)superview {
    // TODO: Implement this method
}

+ (BOOL)isIPad {
    return NO;
}

+ (BOOL)isIPhone {
    return NO;
}

+ (CGFloat)screenWidth {
    return 0.0;
}

+ (CGFloat)screenHeight {
    return 0.0;
}

+ (CGFloat)statusBarHeight {
    return 0.0;
}

+ (CGFloat)navigationBarHeight {
    return 0.0;
}

@end
