//
//  NetworkManager.m
//  Generated by Framework Auto Builder
//
//  Created on 2025-06-12.
//

#import "NetworkManager.h"

@implementation NetworkManager

+ (instancetype)sharedManager {
    return nil;
}

- (instancetype)initWithBaseURL {
    return nil;
}

- (void)startMonitoring {
    // TODO: Implement this method
}

- (void)stopMonitoring {
    // TODO: Implement this method
}

- (NSURLSessionDataTask *)GET:(NSString *)pathparameters:(NSDictionary * _Nullable)parameters {
    return nil;
}

- (NSURLSessionDataTask *)POST:(NSString *)pathparameters:(NSDictionary * _Nullable)parameters {
    return nil;
}

- (NSURLSessionUploadTask *)uploadFile:(NSString *)filePathpath:(NSString *)pathparameters:(NSDictionary * _Nullable)parametersprogress:(NetworkProgressBlock _Nullable)progress {
    return nil;
}

- (void)cancelAllRequests {
    // TODO: Implement this method
}

@end
